// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0iAH7MS82zShkXm_54AGDw4D06X1ARjQ',
    appId: '1:494981261645:web:bf2f5b8f9a353987ac6f04',
    messagingSenderId: '494981261645',
    projectId: 'styleme-f9451',
    authDomain: 'styleme-f9451.firebaseapp.com',
    storageBucket: 'styleme-f9451.firebasestorage.app',
    measurementId: 'G-WM5V1844KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZlWYMgvf6gF0BwBRh7gDBX3kAo1awF0',
    appId: '1:494981261645:android:f1fe4e1ed0b3e5c8ac6f04',
    messagingSenderId: '494981261645',
    projectId: 'styleme-f9451',
    storageBucket: 'styleme-f9451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVzpES7mEnXWIkLMUdI2H39wgg7pkDC0E',
    appId: '1:494981261645:ios:5455d1116e2538cfac6f04',
    messagingSenderId: '494981261645',
    projectId: 'styleme-f9451',
    storageBucket: 'styleme-f9451.firebasestorage.app',
    iosBundleId: 'com.example.styleme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVzpES7mEnXWIkLMUdI2H39wgg7pkDC0E',
    appId: '1:494981261645:ios:5455d1116e2538cfac6f04',
    messagingSenderId: '494981261645',
    projectId: 'styleme-f9451',
    storageBucket: 'styleme-f9451.firebasestorage.app',
    iosBundleId: 'com.example.styleme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0iAH7MS82zShkXm_54AGDw4D06X1ARjQ',
    appId: '1:494981261645:web:a30e84b3e83bad98ac6f04',
    messagingSenderId: '494981261645',
    projectId: 'styleme-f9451',
    authDomain: 'styleme-f9451.firebaseapp.com',
    storageBucket: 'styleme-f9451.firebasestorage.app',
    measurementId: 'G-T01PXXNBV8',
  );
}
